const translationEn = {
  yourRecipes: "Your recipes",
  recipes: "Recipes",
  yourMenu: "Your Menu",
  startCooking: "Start cooking",
  close: "Close",
  add: "Add",
  addMeal: "Add a meal",
  addDish: "Add a dish",
  addRecipe: "Add recipe",
  addYourRecipe: "Add your recipe",
  yourDish: "Your dish",
  nameAddMealTitle: "Name your meal and add it",
  chooseMeal: "Which meal do you want to add this dish to?",
  enterName: "Enter a name",
  categorys: "Category",
  addMenu: "Add your menu for these days",
  previousWeek: "Previous week",
  nextWeek: "Next week",
  yes: "Yes",
  delete: "Are you sure you want to delete this recipe?",
  noRecipe: "You have no recipes",
};
export default translationEn;
