const translationUa = {
  yourRecipes: "Твої рецепти",
  recipes: "Рецепти",
  yourMenu: "Твоє меню",
  startCooking: "Почати готувати",
  close: "Закрити",
  add: "Додати",
  addMeal: "Додати прийом їжі",
  addDish: "Додати страву",
  addRecipe: "Додати  рецепт",
  addYourRecipe: "Додати свій рецепт",
  yourDish: "Твоя страва",
  nameAddMealTitle: "Назви свій прийом їжі та додай його",
  chooseMeal: "До якого прийому їжі ти хочеш додати цю страву?",
  enterName: "Введіть назву",
  categorys: "Категорії",
  addMenu: "Додай своє меню на ці дні",
  previousWeek: "Попередній тиждень",
  nextWeek: "Наступний тиждень",
  yes: "Так",
  delete: "Ви дійсно хочете видалити цей рецепт?",
  noRecipe: "У вас немає рецептів",
};
export default translationUa;
